export const Message = {
  userMessage: {
    SignUp: "User Sign-up Successfully",
    SignInUser: "User Sign-in Successfully",
    SignInAgent: "Agent Sign-in Successfully",
    SignInAdmin: "Admin Sign-in Successfully",
    VerifyEmail: "OTP send for E-mail Verifycation",
    VerifyOtp: "OTP is Right",
    ForgotPassword: "Otp Send",
    ResetPassword: "Password Reset Successfully",
    ChangePassword: "Password Change Successfully",
    GetCurrentUser: "User Fetch Successfully",
    ChangeProfilePic: "Profile Picture Change Successfully",
    DeleteProfilePic: "Profile Picture Delete Successfully",
    GoogleLoginUser: "New User Created Using Google",
    TotalUser: "Total User Count",
    LogOut: "Log-Out Successfully",
  },
  propertyMessage: {
    AddProperty: "Property Add Successfully",
    GetAllProperty: "List Of All Property",
    GetUserAllProperty: "List Of User All Property",
    GetUserPendingProperty: "List Of User Pending Property",
    GetUserApprovalProperty: "List Of User Approval Property",
    GetUserCancelProperty: "List Of User Cancel Property",
    GetOnlySellProperty: "List Of Sell Property",
    GetOnlyRentProperty: "List Of Rent Property",
    SetApproveProperty: "Property Status :- Approval",
    SetCancelProperty: "Property Status :- Cancel",
    TotalProperty: "Total Property Count",
    TotalRentProperty: "Total Rent Property Count",
    TotalSellProperty: "Total Sell Property Count",
  },
  agentMessage: {
    AddAgent: "Agent Sign-up Successfully",
    GetAllAgent: "List Of All Agent",
    AgentMetting: "Email Send Successfully",
    TotalAgent: "Total Agent Count",
  },
  errorMessage: {
    NotEnterValidFeilds: "Please Enter Valid Fiedls",
    SelectValidRole: "Select USER role",
    UserAlreadyExits: "User Already Exits",
    UserNotExits: "User Not Exits",
    InvalidCredentials: "Invalid User credentials",
    OtpNotSend: "OTP Not Send",
    OtpWrong: "OTP is Wrong",
    PasswordWrong: "Invalid Old Password",
    UnauthorizedRequest: "Unauthorized Request",
    InvalidUserToken: "Invalid Access Token",
    ProfilePicNotFound: "Profile Picture Not Found",
    InvalidData: "Invalid Data",
    UserCantChange: "User Can Not Change",
    UserCantSee: "User Can Not See",
    UserCantSeeTotal: "User Can Not See Total Property",
    UserCantSee: "User Can Not See All User",
    PropertyNotFound: "Property Does Not Found",
    UserNotFound: "User Does Not Found",
    AgentNotFound: "Agent Does Not Found",
    AgentAlreadyExits: "Agent Already Exits",
  },
  emailMessage: {
    SignupSubject: "Signup Successfully in Home Hub Market",
    VerifyEmailSubject: "Verify Email OTP",
    ForgotPasswordSubject: "Forget Password OTP",
  },
};
